spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/reservation-system
    username: sa
    password: 4130
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql : true
    open-in-view: false


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace